### Registration with email
POST localhost:8080/auth/registrationWithEmail
Content-Type: application/json

{
  "name": "Muzaffar",
  "surname": "Ortiqov",
  "email": "e@gmail.com",
  "password": "M12345678m!"
}

### Registration with Phone number
POST localhost:8080/auth/registrationWithPhone
Content-Type: application/json

{
  "name": "Muzaffar",
  "surname": "Ortiqov",
  "email": "muzaffarmike2@gmail.com",
  "phone": "998942702363",
  "password": "M12345678m!"
}

### Verfication with SMS
GET localhost:8080/auth/verificationWithSms
Content-Type: application/json

{
  "phone": "998942702363",
  "message": "Bu Eskiz dan test"
}


### LOGIN WITH EMAIL
POST localhost:8080/auth/loginWithEmail
Content-Type: application/json

{
  "email": "muzaffarmike2@gmail.com",
  "password": "M12345678m!"
}

### LOGIN WITH PHONE NUMBER
POST localhost:8080/auth/loginWithPhone
Content-Type: application/json

{
  "phone": "998942702363",
  "password": "M12345678m!"
}

### Resend Email

POST localhost:8080/auth/resendEmail
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTcwNjM0MzEsImlkIjoxMywicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcxNzE0OTgzMSwiaXNzIjoiS3VuVXpUZXN0In0.TpnlcQs8OOBxVowmvBqHnpeiounmjYthA_-Oe1eJqwTklukugKDOiW-LEPtefw6rY6jEpOUxUaVD01smnaKFXA


### Resend code

POST localhost:8080/auth/resendCode?phone=998942702363


### VERIFICATION WITH EMAIL

GET localhost:8080/auth/verificationWithEmail/eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTcwNTU3MzAsImlkIjoxMiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcxNzE0MjEzMCwiaXNzIjoiS3VuVXpUZXN0In0.Brx0UgHTOcfEx9rAeX4jQIXAWYX8YsLt7p-EZD0uCZg90QeknvEUWrrYoQmCJWTsFRwIboaCHc_b4DlctGBoRQ
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTcwNTU3MzAsImlkIjoxMiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcxNzE0MjEzMCwiaXNzIjoiS3VuVXpUZXN0In0.Brx0UgHTOcfEx9rAeX4jQIXAWYX8YsLt7p-EZD0uCZg90QeknvEUWrrYoQmCJWTsFRwIboaCHc_b4DlctGBoRQ







