### CREATE CATEGORY
POST localhost:8080/category/adm/create
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW5qb24=

{
  "orderNumber": 4,
  "nameUz": "category4 UZ",
  "nameEn": "category4 EN",
  "nameRu": "category4 RU"
}

### UPDATE CATEGORY
PUT localhost:8080/category/adm/update/2
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW5qb24=

{
  "orderNumber": 4,
  "nameUz": "category4 Uz",
  "nameEn": "category4 En",
  "nameRu": "category4 Ru"
}

### DELETE BY ID
DELETE localhost:8080/category/adm/delete/2
Authorization: Basic YWRtaW46YWRtaW5qb24=

### GET ALL CATEGORIES
GET localhost:8080/category/adm/all
Authorization: Basic YWRtaW46YWRtaW5qb24=

### GET ALL BY LANGUAGE
GET localhost:8080/category/lang
Accept-Language: EN
Authorization: Basic TXV6YWZmYXI6bXV6YWZmYXI=
