### CREATE PROFILE
POST localhost:8080/profile/adm/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTcyNTk1ODYsImlkIjoxNSwidXNlcm5hbWUiOiJtdXphZmZhcm1pa2UyQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzE3MzQ1OTg2LCJpc3MiOiJLdW5VelRlc3QifQ.986iykakAM5PrYDprdxBnG7liDV8seuJQj9IGXDBY6k0OFwZZDoM7c9O9bAb4vzD3Z1E9f3UzZ-hMUlXKJ_hIQ

{
  "name": "Alish",
  "surname": "Aliyev",
  "email": "ortiqovmuzaaaffar171@gmail.com",
  "phone": "998942702063",
  "password": "M12345678m!"

}

### GET ALL PROFILES
GET localhost:8080/profile/adm/page?page=1&size=3
Authorization: Basic YWRtaW46YWRtaW5qb24=


### UPDATE PROFILE PHOTO

PUT localhost:8080/profile/updatePhoto/17?photo_id=3
Authorization: Basic TXV6YWZmYXI6bXV6YWZmYXI=

### UPDATE USER
PUT localhost:8080/profile/current/17
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW5qb24=

{
  "name": "Mike",
  "surname": "Black"
}

### FILTER
POST localhost:8080/profile/adm/filter?page=1&size=3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTg3Njc0OTgsImlkIjoxOSwidXNlcm5hbWUiOiJtdXphZmZhcnJybWlrZTJAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfUFVCTElTSCIsImV4cCI6MTcxODg1Mzg5OCwiaXNzIjoiS3VuVXpUZXN0In0.WkZ1mXJu4rQFTYrZlVj3mBNBmKQM1CVDmmXjL45gpuA8fj1KlHF7xlkgxpsiRw7m3VRnx0WGp1POjpKpOVrzhw

{
  "name": "Muzaffar"
}

